export const ValidateProfileErrors = {
    NO_DATA: 'NO_DATA',
    INCORRECT_LENGTH: 'INCORRECT_LENGTH',
    REQUIRED: 'REQUIRED',
    SERVER_ERROR: 'SERVER_ERROR',
    INCORRECT_AGE: 'INCORRECT_AGE',
} as const
